/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      keepAlive: true,
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      keepAlive: true,
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      keepAlive: true,
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 10,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'application',
    path: '/application',
    component: 'layout.base$view.application',
    meta: {
      title: 'application',
      i18nKey: 'route.application',
      keepAlive: true,
      order: 3,
      icon: 'material-symbols:assistant-direction-outline-rounded'
    }
  },
  {
    name: 'chat',
    path: '/chat',
    component: 'layout.base$view.chat',
    meta: {
      title: 'chat',
      i18nKey: 'route.chat',
      icon: 'material-symbols:chat-bubble-outline-rounded',
      order: 2,
      keepAlive: true
    }
  },
  {
    name: 'chat-share',
    path: '/chat-share/:id',
    component: 'layout.blank$view.chat-share',
    props: true,
    meta: {
      title: 'chat-share',
      i18nKey: 'route.chat-share',
      hideInMenu: true,
      constant: true,
      keepAlive: true
    }
  },
  {
    name: 'drawing',
    path: '/drawing',
    component: 'layout.base',
    redirect: '/drawing/home',
    meta: {
      title: 'drawing',
      i18nKey: 'route.drawing',
      icon: 'material-symbols:photo-auto-merge-outline-rounded',
      keepAlive: true,
      order: 4,
      multiTab: false
    },
    children: [
      {
        name: 'drawing_home',
        path: '/drawing/home',
        component: 'view.drawing_home',
        meta: {
          title: 'drawing_home',
          i18nKey: 'route.drawing_home',
          hideInMenu: true,
          keepAlive: true
        }
      },
      {
        name: 'drawing_tool',
        path: '/drawing/tool/:name',
        component: 'view.drawing_tool',
        meta: {
          title: 'drawing_tool',
          hideInMenu: true,
          i18nKey: 'route.drawing_tool',
          keepAlive: true
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      keepAlive: true
    }
  },
  {
    name: 'invite',
    path: '/invite',
    component: 'layout.base',
    meta: {
      title: 'invite',
      i18nKey: 'route.invite',
      icon: 'material-symbols:design-services-outline-rounded',
      order: 6,
      keepAlive: true
    },
    children: [
      {
        name: 'invite_pay',
        path: '/invite/pay',
        component: 'view.invite_pay',
        meta: {
          title: 'invite_pay',
          i18nKey: 'route.invite_pay',
          icon: 'prime:money-bill',
          keepAlive: true
        }
      },
      {
        name: 'invite_user',
        path: '/invite/user',
        component: 'view.invite_user',
        meta: {
          title: 'invite_user',
          i18nKey: 'route.invite_user',
          icon: 'ep:promotion',
          keepAlive: true
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'voice',
    path: '/voice',
    component: 'layout.base$view.voice',
    meta: {
      title: 'voice',
      i18nKey: 'route.voice',
      keepAlive: true,
      icon: 'material-symbols:sound-detection-loud-sound-outline-rounded',
      order: 5
    }
  }
];
